modLoader = "javafml"
loaderVersion = "[33,)"
issueTrackerURL = "https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile = "icon.png"
authors = "shedaniel"
license = "MIT"

[[mods]]
modId = "roughlyenoughitems"
version = "${version}"
displayName = "Roughly Enough Items (REI)"
description = '''
To allow players to view items and recipes.
'''

[[mods]]
modId = "jei"
version = "8.9999"
displayName = "Roughly Enough Items (JEI Stub)"
description = '''
To allow players to view items and recipes.
'''

[[dependencies.roughlyenoughitems]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.22,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roughlyenoughitems]]
modId = "cloth_config"
mandatory = true
versionRange = "[5.1,)"
ordering = "NONE"
side = "BOTH"
