modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/shedaniel/RoughlyEnoughItems/issues"
logoFile = "icon.png"
authors = "shedaniel"
license = "MIT"
[[mods]]
modId = "roughlyenoughitems"
version = "${version}"
displayName = "Roughly Enough Items"
description = '''
To allow players to view items and recipes.
'''

[[dependencies.roughlyenoughitems]]
modId = "architectury"
mandatory = true
versionRange = "[1.9.136,)"
ordering = "NONE"
side = "BOTH"
