name: Java CI

on:
  push:
    branches:
      - 3.x
      - 4.x-unstable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Upload to CurseForge
        run: ./gradlew clean build curseforge --refresh-dependencies --stacktrace
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
